name: DevOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-portfolio:test .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "devops-portfolio:test"
          format: "table"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

      - name: Run container
        run: |
          docker run -d \
            --name devops-test \
            -p 8080:80 \
            devops-portfolio:test

      - name: Test application
        run: |
          sleep 5
          curl --fail http://localhost:8080

      - name: Stop container
        if: always()
        run: docker rm -f devops-test